### ISSUE TITLE
Menu links and URLs

### ISSUE THREAD

**Issue by rskikuli** [JoraKasapi/jorakasapi.github.io#13]
There are some inconsistencies in the links that are shown in the menu. More specifically:

**Homepage:** 

- [x] blog: there are two 'blog' links at the moment. Keep only the one that redirects to https://medium.com/@jorakasapi
- [ ] portfolio: should redirect to https://jorakasapi.github.io/portfolio.html (important: see this issue #11 before proceeding)
- [ ] 'home' button does not have an active link. I assume it will have jorakasapi.com

**Contact**

- [ ] 'home' button does not have an active link. I assume it will have jorakasapi.com
- [ ] portfolio: should redirect to https://jorakasapi.github.io/portfolio.html (important: see this issue #11 before proceeding)
- [x] blog: there are two 'blog' links at the moment. Keep only the one that redirects to https://medium.com/@jorakasapi

**Portfolio**

- [ ] 'home' button does not have an active link. I assume it will have jorakasapi.com
- [ ] portfolio: should redirect to https://jorakasapi.github.io/portfolio.html (important: see this issue #11 before proceeding)
- [x] blog: there are two 'blog' links at the moment. Keep only the one that redirects to https://medium.com/@jorakasapi

**About**
- [ ] 'home' button does not have an active link. I assume it will have jorakasapi.com
- [ ] portfolio: right now it sends to https://jorakasapi.github.io/about.html. It should redirect to https://jorakasapi.github.io/portfolio.html (important: see this issue #11 before proceeding)
- [x] blog: there are two 'blog' links at the moment. Keep only the one that redirects to https://medium.com/@jorakasapi
